### ISSUE TITLE
Option to generate more compact syntax

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/PropertyChangedAnalyzers#114]
I like my properties as compact as possible:

```cs
private string foo;
public string Foo { get => foo; set => Set(ref foo, value); }

private int bar;
public int Bar { get => bar; set => Set(ref bar, value); }

private bool Set<T>(ref T field, T value, [CallerMemberName] string propertyName = null)
{
    if (RuntimeHelpers.Equals(field, value)) return false;
    field = value;
    OnPropertyChanged(propertyName);
    return true;
}
```

Would it be possible to auto-detect this form and maybe even add a secondary code fix option to generate the `Set` method and use this exact syntax for properties?

Relates to the discussion of name and equality detection in https://github.com/DotNetAnalyzers/PropertyChangedAnalyzers/issues/98. I don't mind the name `TrySetAndNotify`.

**Comment by JohanLarsson** [comment]
Yes it is very possible, not going to be hard. I'm thinking only one fix and detect style is best.

**Comment by jnm2** [comment]
This is working nicely in the latest releases!
