### ISSUE TITLE
'Notify when value changes' failing to detect that field name should not be qualified

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/PropertyChangedAnalyzers#115]
Since the existing accesses of `foo` and `PropertyChanged` are not qualified, there should be nothing ambiguous in the class and newly generated accesses should follow the existing style (or configured C# options):

Self-contained repro (using VS 16.2.0, but I've seen it all the way back to VS 2017 iirc):

##### TestObject.cs

```cs
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace QualifiedAccessRepro
{
    public sealed class TestObject : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        private int foo;

        public int Foo
        {
            get => foo;
            set
            {
                if (foo == value) return;
                foo = value;
                OnPropertyChanged();
            }
        }

        public int Bar { get; set; }

        private void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
```

##### QualifiedAccessRepro.csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PropertyChangedAnalyzers" Version="2.7.2" PrivateAssets="all" />
  </ItemGroup>

</Project>
```

### Outcome

```cs
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace QualifiedAccessRepro
{
    public sealed class TestObject : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        private int foo;

        public int Foo
        {
            get => foo;
            set
            {
                if (foo == value) return;
                foo = value;
                OnPropertyChanged();
            }
        }

        private int bar;

        public int Bar
        {
            get => this.bar;
            set
            {
                if (value == this.bar)
                {
                    return;
                }

                this.bar = value;
                this.OnPropertyChanged();
            }
        }

        private void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
```

**Comment by JohanLarsson** [comment]
Had the field been named `_foo` it would have worked. Do you really want no `this.` and fields not prefixed with `_foo`?

**Comment by jnm2** [comment]
> Do you really want no `this.` and fields not prefixed with `_foo`?

100%. I've been doing it for years, not likely to stop any time soon. I think other people do this too. `this.` is occasionally necessary for disambiguation, but it's rare.

**Comment by JohanLarsson** [comment]
OK, just checkin' guess we need to musser it :D

**Comment by JohanLarsson** [comment]
It will be slightly inconvenient as the signature that check this now is `public static bool UnderscoreFields(this SemanticModel semanticModel)`  https://github.com/GuOrg/Gu.Roslyn.Extensions/blob/master/Gu.Roslyn.CodeFixExtensions/CodeStyle.cs#L28

**Comment by jnm2** [comment]
Don't be too quick to call it mussering; others may beg to differ. :P First example I found is https://github.com/scriptcs/scriptcs/blob/dev/src/ScriptCs.Hosting/LineEditor.cs but I haven't looked very hard yet.

**Comment by jnm2** [comment]
> UnderscoreFields

I'd go by the editorconfig/CodeStyleOptions terminology, e.g. QualifyFieldAccess and UnderscoreFieldPrefix or something like that?

**Comment by JohanLarsson** [comment]
Yes, we make the current obsolete and split it up. Maybe we can dig out the code style from editorconfig? That would be nicer than walking.

**Comment by jnm2** [comment]
Yes. Compiles in my head per source.roslyn.io, probably close to what you want:

```cs
var options = await document.GetOptionsAsync(cancellationToken).ConfigureAwait(false);

var qualifyFieldAccess = options.GetOption(CodeStyleOptions.QualifyFieldAccess);
```

**Comment by jnm2** [comment]
Pushed tests to master and https://github.com/DotNetAnalyzers/PropertyChangedAnalyzers/tree/mussering. This has already been fixed.
