### ISSUE TITLE
Erroring code is generated when the BCL does not declare CallerMemberNameAttribute

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/PropertyChangedAnalyzers#117]
This affects only .NET Framework 4.0 projects and older, so I don't personally think this is a problem.

The generated code has a red squiggle because the name does not exist, and a using directive is not added for it:

```cs
    protected virtual void OnPropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
```

My preferred solution is to declare this in a file called Polyfill.cs:

```cs
namespace System.Runtime.CompilerServices
{
    // Added in .NET Framework 4.5.
    [AttributeUsage(AttributeTargets.Parameter)]
    internal sealed class CallerMemberNameAttribute : Attribute
    {
    }
}
```

but everyone may be different. After doing so, the analyzer acts as expected.

**Comment by JohanLarsson** [comment]
Sorry about this, pretty terrible.

**Comment by jnm2** [comment]
I don't think it's very bad because no one should be using net40 or lower, so it's par for the course. But that's up to you of course. :)
