### ISSUE TITLE
Diagnostic and fix expected for nullable reference property that doesn't notify

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/PropertyChangedAnalyzers#158]
```cs
public sealed class MainViewModel : ViewModel
{
    // No fixes available:
    public string? Foo { get; private set; }
}

public abstract class ViewModel : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler? PropertyChanged;

    protected bool Set<T>(ref T field, T value, [CallerMemberName] string propertyName = null!)
    {
        if (!RuntimeHelpers.Equals(field, value)) return false;
        field = value;
        OnPropertyChanged(propertyName);
        return true;
    }

    protected void OnPropertyChanged([CallerMemberName] string propertyName = null!)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
```

**Comment by JohanLarsson** [comment]
You hit a special case. This is not due to nullable, the analyzer special cases properties that are not mutated outside the constructor.

If you change to either:

```cs
public sealed class MainViewModel : ViewModel
{
    public string? Foo { get; set; }
}
```

Or 

```cs
public sealed class MainViewModel : ViewModel
{
    public string? Foo { get; private set; }

        public void M(string foo)
        {
            this.Foo = foo;
        }
}
```

You should get the warning. Reason it was special cased was xml serilaization iirc. We can change it of course.

**Comment by jnm2** [comment]
Could there be a refactoring without a diagnostic?

**Comment by JohanLarsson** [comment]
There is no support for refactorings via nuget, must be vsix. Why do you want to notify for a property that is not mutated btw? Setting it via reflection?

**Comment by jnm2** [comment]
`get; set;` == mutated from the outside
`get; private set;` == mutated only from the inside
`get;` == not mutated

**Comment by JohanLarsson** [comment]
The special case is for `get; private set;` then the analyzer checks if mutation only happens in ctor. Changing from `get; private set;` is breaking for some serialization.

**Comment by jnm2** [comment]
The fact remains that `{ get; private set; }` is the idiomatic thing to do for one-way data bindings, not `{ get; set; }`, and so I'll often be in this situation.

**Comment by jnm2** [comment]
Sorry, misclick.

**Comment by JohanLarsson** [comment]
But you can bind to `{ get; private set; }`, at least in WPF. I usually make the class `INotifyPropertyChanged` as IIRC there is a memory leak if binding to a member that is not INPC, maybe it was fixed.

**Comment by jnm2** [comment]
> But you can bind to `{ get; private set; }`, at least in WPF.

That's why I'm typing it as `{ get; private set; }` and looking for a refactoring, because I want to bind to it.

> I usually make the class `INotifyPropertyChanged` as IIRC there is a memory leak if binding to a member that is not INPC, maybe it was fixed.

In my example above, the class is INPC.

**Comment by JohanLarsson** [comment]
As soon as the property is mutated somewhere outside the constructor the warning and the fix will show up. If not issue, then we have a bug.

**Comment by jnm2** [comment]
Ah, I didn't pick up on this right away. I'm introducing the property before I even know what the code looks like that would mutate it. I guess I can wait till then and come back later after the warning shows up, rather than making the property look like the other properties.

Since we can't do refactorings, is there any great way to do a silent diagnostic to get the fix showing up without a warning? Or would that require a second diagnostic ID?

**Comment by JohanLarsson** [comment]
I'll change the analyzer to nag for `private set;` when the class is `INPC` I agree this is nicer when writing code. Write the auto property then postfix it to notify.
