### ISSUE TITLE
INPC001 missing option to generate Set method from baseclass

### ISSUE THREAD

**Issue by Insire** [DotNetAnalyzers/PropertyChangedAnalyzers#16]
I get the warning, that this class should implement INPC, which may or may not be valid,
but it should give me the suggestion to implement it the same way i do it everywhere else, instead of only giving me the option to generate the default boilerplate.

I assume you are analyzing this class, because its referenced in a class that implements INPC, you could then pick the base class from there and assume its usage here too.

```cs
namespace Maple
{
    public class FileSystemBrowserOptions
    {
        public bool MultiSelection { get; set; }
        public bool CanCancel { get; set; }
        public string Title { get; set; }
    }
}
```

**Comment by JohanLarsson** [comment]
The reason we warn is that there are public mutable properties in the class. May or may not be right, for the stuff I write I make every public mutable notify when the value changes. Reason for this is to not have to chase binding errors later.

As it is now the fix suggests the following fixes:
1) Implement `INotifyPropertyChanged`
2) Subclass `Caliburn.Micro.PropertyChangedBase`if `Caliburn.Micro` is referenced.
3) Subclass `GalaSoft.MvvmLight.ViewModelBase` if `GalaSoft.MvvmLight` is referenced.

Searching all visible symbols and figure out if it is a `ViewModelBase` type of class is not going to be very fast.

I'm leaning towards that the current implementation is pretty good as it is. You get the warning and can add `FileSystemBrowserOptions : YourViewModelBase` manually if none of the code gen options are to your liking.

**Comment by JohanLarsson** [comment]
I'm closing this, I think adding `: BaseClass` manually for types within the sln is reasonable.
Once there is a subclass the code gen for making properties observable kicks in.
