### ISSUE TITLE
INPC001: should not trigger for internal properties, since they are not bindable

### ISSUE THREAD

**Issue by Insire** [DotNetAnalyzers/PropertyChangedAnalyzers#171]
![grafik](https://user-images.githubusercontent.com/11455827/74103497-a3725c00-4b4c-11ea-90df-026958f70451.png)

**Comment by JohanLarsson** [comment]
Internal properties are bindable if they are in the application/exe project. We can detect that better. Maybe we should split out a separate rule if internal properties should notify to enable configuration.
For the stuff I write I often want internal to notify as I use them with rx and not only bindings.

**Comment by Insire** [comment]
> Internal properties are bindable if they are in the application/exe project.
TIL.

But yeah, this is in a library project and that class should not be bound to.

**Comment by Insire** [comment]
I have a better suggestion/ preferable approach in  #172 , so im closing this one.
