### ISSUE TITLE
Detect and follow backing field placement convention

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/PropertyChangedAnalyzers#58]
Some preferences put the field directly above the property with no blank line separating them, and the property declaration all on one line:

```cs
private int value1;
public int Value1 { get => value1; set => Set(ref value1, value); }

private int value2;
public int Value2 { get => value2; set => Set(ref value2, value); }
```

It would be nice if the code fix detected and followed this style either in the current class or the whole compilation.

**Comment by JohanLarsson** [comment]
Fixed with https://github.com/GuOrg/Gu.Roslyn.Extensions#backingfieldsadjacent
