### ISSUE TITLE
INPC004 does not provide the correct fix when using stylet

### ISSUE THREAD

**Issue by RyadaProductions** [DotNetAnalyzers/PropertyChangedAnalyzers#66]
![image](https://user-images.githubusercontent.com/24586388/37060811-b0633b3c-2191-11e8-889c-63ecdb63a5c5.png)

**Comment by JohanLarsson** [comment]
That was a really dumb bug, sry about that, thanks for reporting. Releasing an update now.

**Comment by JohanLarsson** [comment]
New version: https://www.nuget.org/packages/PropertyChangedAnalyzers/2.5.4
