### ISSUE TITLE
Depending on code style in the project add usings or Full namespace

### ISSUE THREAD

**Issue by RyadaProductions** [DotNetAnalyzers/PropertyChangedAnalyzers#67]
For example instead of adding 
`class Example Stylet.PropertyChangedBase` 
add:
`using Stylet;

class Example : PropertyChangedBase`

depending on the style the user has in their project.

**Comment by JohanLarsson** [comment]
https://www.nuget.org/packages/PropertyChangedAnalyzers/2.5.5
