### ISSUE TITLE
INPC001 should not notify here as well as broken message

### ISSUE THREAD

**Issue by JCBurnside** [DotNetAnalyzers/PropertyChangedAnalyzers#80]
![image](https://user-images.githubusercontent.com/10678224/38461118-3dcba514-3a96-11e8-9488-640d64997204.png)
![image](https://user-images.githubusercontent.com/10678224/38461119-44c696c6-3a96-11e8-83f0-347216d4ac13.png)
IRCBot does not impliment INPC thus does not need to notify.

**Comment by JCBurnside** [comment]
Message was fixed by restarting VS.

**Comment by JohanLarsson** [comment]
Why should the property not notify?
