### ISSUE TITLE
Use expression body accessors

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/PropertyChangedAnalyzers#91]
R# has it already but why not.

**Comment by sharwell** [comment]
Roslyn has this in the IDE layer, and we really want to get it moved to the code style layer for compiler enforcement.

**Comment by JohanLarsson** [comment]
Ah, ok I can never tell what is r# and what is VS. They probably both have it. I'm leaving this open any way maybe I'll write it if bored, should just be thirty minutes or so.
